sudo: required

dist: xenial

services:
  - docker

language: bash

install:
  - wget -N https://github.com/multiarch/qemu-user-static/releases/download/v3.0.0/x86_64_qemu-arm-static.tar.gz
  - tar -xvf x86_64_qemu-arm-static.tar.gz

before_script:
  # TODO: explain
  - sed -ie 's/FROM alpine/FROM arm32v6\/alpine/g' Dockerfile

  # TODO: explain
  - sed -ie 's/FROM meedamian\/berkeleydb:db-4.8.30.NC/FROM meedamian\/berkeleydb:linux-arm-db-4.8.30.NC/g' Dockerfile

  - mkdir -p ~/.docker
  - >
    echo '{ "experimental": "enabled" }' > ~/.docker/config.json

  - sudo systemctl restart docker

script:
  - docker build --no-cache -t bitcoind .

after_success:
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      travis_retry timeout 5m echo "$DOCKER_PASS" | docker login -u="$DOCKER_USER" --password-stdin
    ./travis-deploy.sh
    fi

